package com.flight.user.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "ticketbooking")
public class TicketBooking {
	@DynamoDBHashKey(attributeName = "pnrNumber")
	@DynamoDBAutoGeneratedKey
	private String pnrNumber;
	@DynamoDBAttribute
	private String fromCity;
	@DynamoDBAttribute
	private String endCity;
	@DynamoDBAttribute
	private String flightName;
	@DynamoDBAttribute
	private String totalPriceAmount;
	@DynamoDBAttribute
	private String flightCode;
	@DynamoDBAttribute
	private String userName;
	@DynamoDBAttribute
	private String email;

	public TicketBooking() {
		super();
		// TODO Auto-generated constructor stub
	}

	public TicketBooking(String pnrNumber, String fromCity, String endCity, String flightName, String totalPriceAmount,
			String flightCode, String userName, String email) {
		super();
		this.pnrNumber = pnrNumber;
		this.fromCity = fromCity;
		this.endCity = endCity;
		this.flightName = flightName;
		this.totalPriceAmount = totalPriceAmount;
		this.flightCode = flightCode;
		this.userName = userName;
		this.email = email;
	}

	@Override
	public String toString() {
		return "TicketBooking [pnrNumber=" + pnrNumber + ", fromCity=" + fromCity + ", endCity=" + endCity
				+ ", flightName=" + flightName + ", totalPriceAmount=" + totalPriceAmount + ", flightCode=" + flightCode
				+ ", userName=" + userName + ", email=" + email + "]";
	}

	public String getPnrNumber() {
		return pnrNumber;
	}

	public void setPnrNumber(String pnrNumber) {
		this.pnrNumber = pnrNumber;
	}

	public String getFromCity() {
		return fromCity;
	}

	public void setFromCity(String fromCity) {
		this.fromCity = fromCity;
	}

	public String getEndCity() {
		return endCity;
	}

	public void setEndCity(String endCity) {
		this.endCity = endCity;
	}

	public String getFlightName() {
		return flightName;
	}

	public void setFlightName(String flightName) {
		this.flightName = flightName;
	}

	public String getTotalPriceAmount() {
		return totalPriceAmount;
	}

	public void setTotalPriceAmount(String totalPriceAmount) {
		this.totalPriceAmount = totalPriceAmount;
	}

	public String getFlightCode() {
		return flightCode;
	}

	public void setFlightCode(String flightCode) {
		this.flightCode = flightCode;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
